SELECT EXTRACT(MONTH FROM DTNASCIMENTO) AS MES,
COUNT(*) AS QUANTIDADE,
SUM(SALARIO*0.05) AS TOTALBONUS
FROM FUNCIONARIO
GROUP BY EXTRACT(MONTH FROM DTNASCIMENTO)
HAVING COUNT(*)>1
ORDER BY EXTRACT(MONTH FROM DTNASCIMENTO);